services:
  users:
    build: ./users_microservice
    command: uvicorn main:app --host 0.0.0.0 --reload --proxy-headers --forwarded-allow-ips "*"
    volumes:
      - ./users_microservice:/app
    container_name: ag-users
    environment:
      - POSTGRES_DB=agency
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
    expose:
      - "8000"
    depends_on:
      - postgresql

  apartments:
    build: ./apartments_microservice
    command: uvicorn main:app --host 0.0.0.0 --reload --proxy-headers --forwarded-allow-ips "*"
    volumes:
      - ./apartments_microservice:/app
    container_name: ag-apartments
    environment:
      - POSTGRES_DB=agency
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
    expose:
      - "8000"
    depends_on:
      - postgresql

  frontend:
    container_name: ag-frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    restart: always
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    container_name: ag-nginx
    depends_on:
      - users
      - apartments
      - frontend

  postgresql:
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=agency
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: ag-psql
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/

volumes:
  postgresql_volume:

